import '@/app/globals.css';
import type { Metadata } from 'next';
import { Bricolage_Grotesque } from 'next/font/google';

const font = Bricolage_Grotesque({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} bg-background-neutral-default text-foreground-neutral-default flex min-h-dvh flex-col antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
